### ISSUE TITLE
Dishes Reviews

### ISSUE THREAD

**Issue by Andrew-Wichmann** [SIU-CS/MultiMenu#12]
# As a user, I want to see a dish review before I choose from the menu, so that will help me to have a clear  idea about the dishes.
### Acceptance criteria:

1. User click on the dish's name then droplist will show many options one of them is the review.
2. User select the review option .
3. The application will take the user to the page review where he can read people reviews.

**Comment by techAbhi1461** [comment]
Finished Dish Reviews
