### ISSUE TITLE
Visually Appealing

### ISSUE THREAD

**Issue by techAbhi1461** [SIU-CS/MultiMenu#2]
# As a general customer and a store owner, I want the application to be visually appealing
So the the experience is memorable and easy to use.

### Acceptance criteria:
1. The application will be considered visually appealing when all components of the interface are decorated with appealing fonts, colors, and/or pictures.
2. Users should remember the visual elements of the app a week after using it.
3. The app should have at least one picture, video, or gif.

### Estimate:  12 hours

**Comment by Andrew-Wichmann** [comment]
- Add pictures of food

**Comment by Andrew-Wichmann** [comment]
I like the pictures, but could you rotate the few that are rotated. Also, could you use this image for a hotdog instead? 
![hotdog_mustard-main](https://cloud.githubusercontent.com/assets/11933375/24967323/5658f64c-1f6f-11e7-827a-3175b8e9e544.jpg)

**Comment by Andrew-Wichmann** [comment]
It's just that the sausage picture looks really unappetizing.
@bmcconnell21 @techAbhi1461
